#!/usr/bin/env python3
"""CLI for NanoResFormer - Nanopore Signal Transformer for Gene Detection."""

import argparse
import sys
import os

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from nanoresformer.NanoResFormer_predict import NanoResFormer_predict


def main():
    parser = argparse.ArgumentParser(
        description="Run NanoResFormer inference on signals from sharded NumPy arrays.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    
    # --- Required Arguments ---
    parser.add_argument(
        'index_path', 
        type=str, 
        help='Path to Parquet index file (generated by pod5_extractor.py)'
    )
    parser.add_argument(
        'out_dir', 
        type=str, 
        help='Directory where results (CSV and optional images) will be saved.'
    )
    
    # --- Optional Arguments ---
    parser.add_argument(
        '--csv_name', 
        type=str, 
        default=None, 
        help='Base name for output files (default: uses index filename).'
    )
    parser.add_argument(
        '--OV', 
        type=int, 
        default=80, 
        help='Window overlap percentage (10-99). Default: 80.'
    )
    parser.add_argument(
        '--Model', 
        type=str, 
        default='middle', 
        choices=['low', 'middle', 'high'],
        help="Model variant to use. Default: 'middle'."
    )
    parser.add_argument(
        '--export_images', 
        action='store_true', 
        default=False,
        help='If present, export annotated images for each processed signal. Default: False.'
    )
    parser.add_argument(
        '--device_pref', 
        type=str, 
        default='auto', 
        choices=['auto', 'cpu', 'cuda'],
        help="Device selection preference. Default: 'auto'."
    )
    
    args = parser.parse_args()
    
    try:
        NanoResFormer_predict(
            shard_index_path=args.index_path,
            out_dir=args.out_dir,
            csv_name=args.csv_name,
            OV=args.OV,
            Model=args.Model,
            export_images=args.export_images,
            device_pref=args.device_pref
        )
    except Exception as e:
        print(f"\nERROR: NanoResFormer execution failed. {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
