"""NanoResFormer inference module."""

import os
import numpy as np
import pandas as pd
import torch
from typing import List, Dict, Any, Optional
import sys

from nanoresformer.preprocess.normalize import normalize_signal
from nanoresformer.preprocess.windowing import prepare_windows
from nanoresformer.utils import determine_batch_size, pad_signal, depad_signal, select_device, export_image, model_mapping


def NanoResFormer_predict(
    shard_index_path: str,
    out_dir: str,
    csv_name: Optional[str] = None,
    OV: int = 80,
    Model: str = 'middle',
    export_images: bool = False,
    device_pref: str = 'auto'
) -> str:
    """
    Run NanoResFormer inference on signals from sharded NumPy arrays.

    Parameters
    ----------
    shard_index_path : str
        Path to the Parquet index file for sharded signals.
        Generated by pod5_extractor.py from POD5 files.
    out_dir : str
        Directory where results (CSV and optional images) will be saved.
    csv_name : str, optional
        Base name for output files; if None the input filename (without
        extension) will be used.
    OV : int or float, default=80
        Window overlap percentage (0-99). Determines overlap between
        consecutive sliding windows.
    Model : str, default='middle'
        Model variant to use (e.g., 'middle', 'low', 'high').
    export_images : bool, default=False
        If True, export annotated images for each processed signal.
    device_pref : str, default='auto'
        Device selection preference: 'cpu', 'cuda', or 'auto' to let the
        code choose.

    Returns
    -------
    str
        Path to the CSV file containing aggregated results for all processed signals.
    """

    # Print software / license / citation info
    print("----------------------------------------")
    print("Starting NanoResFormer - Nanopore Signal Transformer for Gene Detection")
    print("Version: 2.0")
    print("Licence: MIT (see project LICENSE file)")
    print("Please cite: Jakubicek et al., Basecalling-free resistance gene identification using a hybrid transformer in raw nanopore signals (2026)")
    print("----------------------------------------")

    print("Starting NanoResFormer inference...")

    # Check if index file exists
    if not os.path.exists(shard_index_path):
        raise FileNotFoundError(f"Index file not found at {shard_index_path}")

    print(f"Input index path: {os.path.abspath(shard_index_path)}")
    print(f"Output directory: {os.path.abspath(out_dir)}")

    print("Loading shard index...")
    from nanoresformer.ingest import ShardIndex
    shard_index = ShardIndex(shard_index_path)
    total_signals = len(shard_index)
    print(f"  - Number of signals found: {total_signals}")

    window_length = 40000
    n_heads = 2
    n_layers = 1
    num_classes = 11
    padding = True

    batch_size = determine_batch_size(window_length, device_pref)

    os.makedirs(out_dir, exist_ok=True)
    
    # Derive csv_name from index path if not provided
    if csv_name is None:
        index_basename = os.path.splitext(os.path.basename(shard_index_path))[0]
        csv_name = f"{index_basename}_results"

    images_dir = os.path.join(out_dir, f"images_{csv_name}")
    if export_images:
        os.makedirs(images_dir, exist_ok=True)

    FullModelClass, model_name, d_model = model_mapping(Model)
    model_path = os.path.join("models", f"{model_name}.pth")

    device = select_device(device_pref)

    print(f"Loading model: {model_name}")

    model = FullModelClass(segment_length=window_length, d_model=d_model, n_heads=n_heads,
                           n_transformer_layers=n_layers, num_classes=num_classes)
    model = model.to(device)
    
    # Check if model file exists BEFORE loading
    if not os.path.exists(model_path):
        raise FileNotFoundError(
            f"Model file not found at {model_path}. "
            "Please ensure the model file is present in the models directory."
        )
    
    model.load_state_dict(torch.load(model_path, map_location=device, weights_only=True))
    model.eval()

    print(f"  - Model file found: {model_path}")
    print(f"  - Device: {device}")

    window_overlap_percent = OV
    window_overlap = int(window_length * window_overlap_percent / 100)
    step = int(window_length - window_overlap)
    if step <= 0:
        raise ValueError("OV too large, resulting in non-positive step size.")

    results_list: List[Dict[str, Any]] = []

    label_colors = [None, "#e6194B", "#0e3ce4", "#f58231", "#911eb4", "#46f0f0", "#009e15",
                    "#f032e6", "#bcf60c", "#5E4219", "#008080"]
    gene_names = [
        "no gene", "blaSHV", "blaOXA", "aac(3)", "aph(6)-Id", "aph(3'')-Ib",
        "OqxA", "OqxB", "tetA", "tetD", "fosA"
    ]

    print("Beginning signal processing and inference...")

    processed_signals = 0
    
    # Iterate over signals in shard index
    for num, record in enumerate(shard_index):
        # Get signal from shard (memory-mapped)
        signal_raw = shard_index.get_signal(record.read_id)
        if signal_raw is None:
            print(f"Warning: Could not load signal for read {record.read_id}")
            continue
        
        signal = normalize_signal(signal_raw)

        if padding:
            signal, pad_left, pad_right = pad_signal(signal, window_length)
        else:
            pad_left = pad_right = 0

        windows, centers = prepare_windows(signal, window_length, step)

        results = []
        model_device = device
        for i in range(0, len(windows), batch_size):
            batch_windows = windows[i:i+batch_size]
            current_centers = centers[i:i+batch_size]
            batch_array = np.stack(batch_windows, axis=0)
            batch_tensor = torch.tensor(batch_array, dtype=torch.float32, device=model_device)
            with torch.no_grad():
                outputs = model(batch_tensor)
                probs = torch.softmax(outputs, dim=1)
                preds = outputs.argmax(dim=1).cpu().numpy().tolist()
                probs_cpu = probs.cpu()

            for b_idx in range(len(preds)):
                klas = int(preds[b_idx])
                prob = probs_cpu[b_idx:b_idx+1, :]
                center = current_centers[b_idx]
                results.append((center, klas, prob))

        klasifikace = [r[1] for r in results]

        # map predicted label indices to gene names, exclude 'no gene' (0) unless no other found
        unique_labels = sorted(set(klasifikace))
        found_labels = [l for l in unique_labels if l != 0]
        if not found_labels:
            found_genes_str = "None"
        else:
            found_genes_str = ";".join(gene_names[l] for l in found_labels)

        results_list.append({
            'num': f"{num:08d}",
            'ID': record.read_id,
            'found_genes': found_genes_str
        })

        # depad for plotting
        if padding:
            signal_plot_arr = depad_signal(signal, pad_left, pad_right)
            centers_plot = [c - pad_left for c in centers]
        else:
            signal_plot_arr = signal
            centers_plot = centers

        if export_images:
            export_image(signal_plot_arr, centers_plot, results, images_dir, num, record.read_id,
                         None if found_genes_str == "None" else found_genes_str,
                         gene_names, label_colors, record.labels)

        # update progress bar only in parts (e.g. ~20 updates over the run)
        processed_signals += 1
        if total_signals > 0:
            interval = max(1, total_signals // 20)  # ~20 updates over the run
            if processed_signals % interval == 0 or processed_signals == total_signals:
                percent = processed_signals * 100.0 / total_signals if total_signals else 100.0
                sys.stdout.write(f"\r  - Processing: {processed_signals}/{total_signals} ({percent:.1f}%)")
                sys.stdout.flush()
        else:
            sys.stdout.write("\r  - Processing: 100% \n")
            sys.stdout.flush()

    # finish progress line
    if total_signals > 0:
        print("\n  - Processing complete.")

    # Build DataFrame once at the end
    results_df = pd.DataFrame(results_list)
    results_csv = os.path.join(out_dir, f"{csv_name}.csv")
    results_df.to_csv(results_csv, index=False)
    return results_csv
